edge:
  - WEB_SERVER:
      port: 8081
  - TCP_MASTER:
      port: 8021
  - TCP_SLAVE:
      - name: "test1"
        host: 127.0.0.1
        port: 10087
      - name: "test2"
        host: 127.0.0.1
        port: 10089
  - SERIAL:
      - name: "serial1"
        dev: "COM7"
        baud: 9600
        dataBits: 8
        stopBits: 1
        parity: "E"

      - name: "serial2"
        dev: "COM7"
        baud: 9600
        dataBits: 8
        stopBits: 1
        parity: "E"